///$tab sublib.logg.test
SUB test.sublib.logg
call sublib.logg.start('A','Loggar A1')
  sleep(1000);
  call sublib.logg.start('Loggar A1')
    sleep(1000);
    call sublib.logg.start('Loggar A2')
    call sublib.logg.start('Loggar A21')
      sleep(1000);
      call sublib.logg.stop
      call sublib.logg.start('Loggar A3')
        sleep(1000);
        call sublib.logg.stop
         call sublib.logg.start('Loggar A3')
        sleep(1000);
        call sublib.logg.stop
      call sublib.logg.start('Loggar A4')
        sleep(1000);
        call sublib.logg.stop
      call sublib.logg.stop
    call sublib.logg.stop
  call sublib.logg.start('Loggar A5')
    sleep(1000);
    call sublib.logg.stop
  call sublib.logg.stop

ENDSUB //test-sublib-logg